#! /usr/bin/env python
import sys
import requests

url = sys.argv[1]

payload = { 'key' : 'value', 'firstname' : 'taylor', 'lastname' : 'jones' }
r = requests.post(url, files=payload)
# r = requests.post('http://requestb.in/xucj9exu', files=dict(foo='bar'))
print r.status_code
print r.text


